---
# tasks file for spatula (panorama)

- name: Panorama system configuration
  vars:
    snippet_file: "panorama_system.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - panorama_system

- name: Panorama management settings
  vars:
    snippet_file: "panorama_setting.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - panorama_setting

- name: Panorama administrator
  vars:
    snippet_file: "panorama_mgt_config_users.xml"
    snippet_xpath: "/config/mgt-config/users"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - panorama_mgt_config_users

- name: Password complexity profile
  vars:
    snippet_file: "panorama_mgt_config_pwd.xml"
    snippet_xpath: "/config/mgt-config/password-complexity"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - panorama_mgt_config_pwd

- name: Panorama log settings
  vars:
    snippet_file: "panorama_log_settings.xml"
    snippet_xpath: "/config/panorama/log-settings"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - panorama_log_settings

- name: Log collector groups
  vars:
    snippet_file: "log_collector_group.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/log-collector-group"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - log_collector_group

- name: Shared tags
  vars:
    snippet_file: "tag.xml"
    snippet_xpath: "/config/shared/tag"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - shared_tag

- name: Panorama template
  vars:
    snippet_file: "template.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/template"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - template

- name: System configuration
  vars:
    snippet_file: "device_system_shared.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - device_system_shared

- name: Security-related device settings
  vars:
    snippet_file: "device_setting.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - device_setting

- name: Device management configuration
  vars:
    snippet_file: "device_mgt_config.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/mgt-config"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - device_mgt_config

- name: Device log settings
  vars:
    snippet_file: "shared_log_settings.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/shared/log-settings"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - shared_log_settings

- name: Zone protection profiles
  vars:
    snippet_file: "zone_protection_profile.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='iron-skillet']/config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - zone_protection_profile

- name: Address objects
  vars:
    snippet_file: "address.xml"
    snippet_xpath: "/config/shared/address"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - shared_address

- name: Log forwarding profiles
  vars:
    snippet_file: "log_settings_profiles.xml"
    snippet_xpath: "/config/shared/log-settings/profiles"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - shared_log_profiles

- name: Custom URL categories
  vars:
    snippet_file: "profiles_custom_url_category.xml"
    snippet_xpath: "/config/shared/profiles/custom-url-category"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - shared_profiles_custom_url_category

- name: Decryption profiles
  vars:
    snippet_file: "profiles_decryption.xml"
    snippet_xpath: "/config/shared/profiles/decryption"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - profiles_decryption

- name: Anti-virus profiles
  vars:
    snippet_file: "profiles_virus.xml"
    snippet_xpath: "/config/shared/profiles/virus"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - profiles_virus

- name: Anti-spyware profiles
  vars:
    snippet_file: "profiles_spyware.xml"
    snippet_xpath: "/config/shared/profiles/spyware"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - profiles_spyware

- name: Vulnerability protection profiles
  vars:
    snippet_file: "profiles_vulnerability.xml"
    snippet_xpath: "/config/shared/profiles/vulnerability"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - profiles_vulnerability

- name: File blocking profiles
  vars:
    snippet_file: "profiles_file_blocking.xml"
    snippet_xpath: "/config/shared/profiles/file-blocking"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - profiles_file_blocking

- name: URL filtering profiles
  vars:
    snippet_file: "profiles_url_filtering.xml"
    snippet_xpath: "/config/shared/profiles/url-filtering"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - profiles_url_filtering

- name: WildFire analysis profiles
  vars:
    snippet_file: "profiles_wildfire_analysis.xml"
    snippet_xpath: "/config/shared/profiles/wildfire-analysis"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - profiles_wildfire_analysis

- name: Security profile group
  vars:
    snippet_file: "profile_group.xml"
    snippet_xpath: "/config/shared/profile-group"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - profile_group

- name: Default security post-rules
  vars:
    snippet_file: "post_rulebase_default_security_rules.xml"
    snippet_xpath: "/config/shared/post-rulebase/default-security-rules"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - post_rulebase_default_security_rules

- name: Block security pre-rules
  vars:
    snippet_file: "pre_rulebase_security.xml"
    snippet_xpath: "/config/shared/pre-rulebase/security"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - pre_rulebase_security

- name: Decryption post-rules
  vars:
    snippet_file: "post_rulebase_decryption.xml"
    snippet_xpath: "/config/shared/post-rulebase/decryption"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - post_rulebase_decryption

- name: Decryption pre-rules
  vars:
    snippet_file: "pre_rulebase_decryption.xml"
    snippet_xpath: "/config/shared/pre-rulebase/decryption"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - pre_rulebase_decryption

- name: Panorama template stack
  vars:
    snippet_file: "template_stack.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/template-stack"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - stack

- name: Device management interface
  vars:
    snippet_file: "device_system_local.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ STACK }}']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - device_system_local

- name: Device group
  vars:
    snippet_file: "device_group.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/device-group"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - devicegroup

- name: Custom reports
  vars:
    snippet_file: "reports_simple.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/reports"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - reports

- name: Report groups
  vars:
    snippet_file: "report_group_simple.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/report-group"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - report_group_simple

- name: Email scheduler
  vars:
    snippet_file: "email_scheduler_simple.xml"
    snippet_xpath: "/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/email-scheduler"
    snippet_xml: "{{ lookup('template', '{{ snippet_dir }}/{{ snippet_file }}') }}"
  panos_type_cmd:
    provider: '{{ credentials }}'
    cmd: 'set'
    xpath: '{{ snippet_xpath }}'
    element: '{{ snippet_xml }}'
  tags:
  - email_scheduler